a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))

print('So tem espacos? ', a.isspace())
print('É um numero? ', a.isnumeric())
print('È alfabetico? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Ésta em maisculo? ', a.isupper())
print('Ésta em minusculo? ', a.islower())
print('Esta capitalizada? ', a.istitle())
